linters-settings:
  govet:
    enable:
      - atomicalign
      - deepequalerrors
      - fieldalignment
      - nilness
      - sortslice
      - unusedwrite
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/jnst/agentic-todo-mcp
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  depguard:
    rules:
      main:
        files:
          - "$all"
        allow:
          - "$gostd"
          - "github.com/jnst/agentic-todo-mcp"
          - "github.com/modelcontextprotocol/go-sdk"
          - "github.com/google/go-cmp"
          - "github.com/uber/mock"

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - copyloopvar
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - revive

issues:
  exclude-rules:
    - text: "at least one file in a package should have a package comment"
      linters:
        - revive
  exclude-use-default: false
  exclude:
    - "G104:"
    - "G304:"
    - "G307:"
  exclude-dirs:
    - vendor
    - .todo
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_test\\.go$"

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
